[cosmological_parameters]
omega_k = 0.0 
ombh2  = 0.02238280 
omch2 = 0.00001
omnuh2 = 0.1308
hubble = 55.67
massless_nu = 2.0293 
massive_nu =  1
sterile_neutrino = 1
sterile_mass_fraction = 1
standard_neutrino_neff	 = 4.048
delta_neff = 1

;helium 
yhe = 0.25  

;reionization
tau = 0.0375    

;inflation Parameters
n_s = 0.8718
log1e10As = 2.987 
k_s = 0.05  
n_run = 0.0    
r_t = 0.0     
n_t = 0.0      

;dark energy equation of state
w = -1.0   
wa = 0.0   

[planck]
a_planck    = 1.0
