[setup]
boxlength		= 200
zstart			= 199.0
levelmin		= 8
levelmin_TF		= 8
levelmax		= 12
padding			= 8 
overlap			= 4
ref_center		= 0.5, 0.5, 0.5
ref_extent		= 0.2, 0.2, 0.2
align_top		= no
baryons			= yes
use_2LPT		= no
use_LLA			= yes
periodic_TF		= yes

[cosmology]
Omega_m			= 0.495
Omega_L			= 0.505
w0			= -1.0
wa			= 0.0
Omega_b			= 0.04865393405
H0			= 55.64
sigma_8			= 0.824398
## CAMB angus_nils.ini, sigma_8 = 0.0018
nspec			= 0.872
transfer		= camb_file
transfer_file = ../angus_opt_transfer_out_z199.dat

[random]
seed[7]			= 36511
seed[8]			= 71621
seed[9]			= 22759
seed[10]		= 69822
seed[11]		= 52953
seed[12]		= 91170

[output]
format			= grafic2	
filename		= ics_opt_nu2025_b200l12
ramses_nml		= no

[poisson]
fft_fine		= yes
accuracy		= 1e-5
pre_smooth		= 3
post_smooth		= 3
smoother		= gs
laplace_order		= 6
grad_order		= 6
