#!/bin/sh
#SBATCH --time=00:30:00
#SBATCH --mail-user=nicksam@sirrah.troja.mff.cuni.cz
#SBATCH --mail-type=BEGIN
#SBATCH --job-name="check"
#SBATCH -p ffa-short
#SBATCH -N 1
#SBATCH --mem-per-cpu=50G
#SBATCH -n 16 

srun ./ACO_code ramses2gadget_015.1

